name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: '8.6'
        cabal-version: '3.0'

    - name: Freeze deps
      run: cabal freeze

    - uses: actions/cache@v2
      name: Cache cabal store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ hashFiles('cabal.project.freeze') }}

    - name: Generate site
      run: cabal run

    - name: Deploy site
      uses: s0/git-publish-subdir-action@v2.5.1
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
